### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by digitxo** [Arkq/openaptx#2]
No package 'bluez' found <- https://github.com/Arkq/bluez-alsa <- trying to install that <- heres the problem -> bluez is already the newest version (5.50-1+rpt1).

How can I install this over my existing installation and use it

**Comment by Arkq** [comment]
This issue tracker is not for bluez-alsa repository :)
PS. "bluez is already the newest version" - you need development package mostly suffixed with "-devel" or "-dev".
