### ISSUE TITLE
Bluealsa crash when using aptX

### ISSUE THREAD

**Issue by alex14641** [Arkq/openaptx#3]
When running mplayer with multiple files with a set of headphones supporting AptX, bluealsa crashes when mplayer switches files. Investigation led to attempting to free the same memory twice: in file aptx-ffmpeg.c line 137 from the openaptx project,
encoder_ctx_free is called; in a2dp-audio.c, a thread cleanup handler is also freeing the context. This double free causes bluealsa to crash. I removed the thread cleanup handler call from a2dp-audio.c, and this fixes the crash. Here's a link to a patch.

[a2dp-audio.c.patch.txt](https://github.com/Arkq/bluez-alsa/files/5114483/a2dp-audio.c.patch.txt)

**Comment by Arkq** [comment]
This issue should be resolved with following commits:
- openaptx: https://github.com/Arkq/openaptx/commit/dfb814c3e463d94f26e9f4ca01073226d5b53706
- bluez-alsa: https://github.com/Arkq/bluez-alsa/commit/d155e3077b41f5d2509ca9e61b4780531711ac7d

**Comment by alex14641** [comment]
These changes resolve the issue for me.

Thanks.
