### ISSUE TITLE
Is configure missing?  Don't know how to make it.

### ISSUE THREAD

**Issue by kskenyon** [Arkq/openaptx#4]
cmake -DENABLE_DOC=ON -DWITH_FFMPEG=ON -DWITH_SNDFILE=ON -DENABLE_APTX422=ON -DENABLE_APTXHD100=ON  ..
CMake Warning at CMakeLists.txt:22 (message):
  Building apt-X / apt-X HD with FFmpeg: Compiling openaptx with FFmpeg as an
  encoding backend requires apt-X Adaptive API support in the client code.
  Otherwise, client will not be able to free resources allocated with the
  aptxbtenc_init() function.

CMake Error at src/CMakeLists.txt:24 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "aptx-4.2.2".

CMake Error at src/CMakeLists.txt:38 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "aptxHD-1.0.0".

CMake Error at src/CMakeLists.txt:89 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "aptx".

CMake Error at utils/CMakeLists.txt:25 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "aptxdec".

-- Configuring incomplete, errors occurred!
See also "/home/pi/openaptx/build/CMakeFiles/CMakeOutput.log".

**Comment by Arkq** [comment]
Which version of cmake you are using?

**Comment by kskenyon** [comment]
3.13.  Raspberry pi buster distro installation. 

Kevin

Fatfingered from my iPhone

**Comment by Arkq** [comment]
Please check with current master. I hope it will work now :)

**Comment by dmcallejo** [comment]
Just came here to open this issue as I couldn't build the lib yesterday. Ha, good that someboy already reported it. I can confirm it is working now. Same environment as @kskenyon : `cmake version 3.13.4` on a raspberry pi zero with raspbian.

**Comment by Arkq** [comment]
@dmcallejo OK, thanks for confirmations :)

**Comment by kskenyon** [comment]
Got beat to confirming the fix.  Works great now.  Thanks,

Kevin
