### ISSUE TITLE
Decode very slow on Raspberry Pi Zero

### ISSUE THREAD

**Issue by MrBuddyCasino** [Arkq/openaptx#7]
I compiled from source using the WITH_FFMPEG backend. Playback is not possible, decode speed is lower than realtime. Using AAC I get 13% CPU usage.

Is this a problem in ffmpeg? Not sure where to raise this issue.

**Comment by Arkq** [comment]
I assume that you are using openaptx with bluez-alsa. If that's true, please switch to libopenaptx (unless you are using proprietary Qualcomm libraries), that should give you better overall performance.

**Comment by MrBuddyCasino** [comment]
That fixed it, thanks. Maybe the readme could be updated to recommend libopenaptx?

**Comment by Arkq** [comment]
> Maybe the readme could be updated to recommend libopenaptx?

Yes, you are right. I'll do that :)
